# docker-compose.yml
services:
  ampsassist:
    build: .
    container_name: ampsassist_runner
    restart: unless-stopped
    volumes:
      - plex_music:/app/downloads
      - ./browser.json:/app/browser.json
    environment:
      - TZ=Australia/Sydney
      - PYTHONUNBUFFERED=1

volumes:
  plex_music:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.1.230/music"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},file_mode=0777,dir_mode=0777,vers=3.0"