# docker-compose.yml
services:
  ampsassist:
    build: .
    container_name: ampsassist_runner
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./browser.json:/app/browser.json
    environment:
      - TZ=Australia/Sydney # Ensures your 30-minute scheduler runs on your local time
      - YTM_CLIENT_ID=${YTM_CLIENT_ID}
      - YTM_CLIENT_SECRET=${YTM_CLIENT_SECRET}
      - PYTHONUNBUFFERED=1 # Ensures real-time logging in Docker